# Generated by Django 2.2 on 2019-04-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muscle',
            name='ar_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
