# Generated by Django 2.2 on 2019-04-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muscles', '0002_muscle_ar_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Muscle',
            new_name='MuscleGroup',
        ),
    ]
