# Generated by Django 2.2 on 2019-04-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muscles', '0003_auto_20190406_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ar_name', models.CharField(max_length=255)),
                ('muscle_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='muscles.MuscleGroup')),
            ],
        ),
    ]
